# Generated by Django 4.1.3 on 2022-12-12 21:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0001_initial'),
        ('environment', '0001_initial'),
        ('opmode', '0001_initial'),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('related_task', models.CharField(blank=True, max_length=200)),
                ('refurl_1', models.URLField(blank=True)),
                ('refurl_2', models.URLField(blank=True)),
                ('refurl_3', models.URLField(blank=True)),
                ('refurl_4', models.URLField(blank=True)),
                ('refurl_5', models.URLField(blank=True)),
                ('cmd_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_published', models.BooleanField(default=False)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogue.catalogue')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='environment.environment')),
                ('opmode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='opmode.opmode')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
