# Generated by Django 4.1.3 on 2022-12-14 10:47

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
        ('clicommands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='environment',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='catalogue', chained_model_field='catalogue', on_delete=django.db.models.deletion.DO_NOTHING, to='environment.environment'),
        ),
    ]
