# Generated by Django 4.1.3 on 2022-12-14 11:13

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('opmode', '0001_initial'),
        ('clicommands', '0002_alter_command_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='opmode',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='environment', chained_model_field='environment', on_delete=django.db.models.deletion.DO_NOTHING, to='opmode.opmode'),
        ),
    ]
