# Generated by Django 4.1.3 on 2022-12-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clicommands', '0004_alter_command_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='related_task',
        ),
    ]
