# Generated by Django 4.1.3 on 2022-12-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmd_writer',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
