# Generated by Django 4.1.3 on 2023-02-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_delete_cmd_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jobtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
