# Generated by Django 4.1.3 on 2023-02-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_facebook_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='09_Avocato_Hexacato', upload_to='profile_images'),
        ),
    ]
