# Generated by Django 4.1.3 on 2023-03-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_is_published_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_published',
        ),
        migrations.AddField(
            model_name='profile',
            name='Published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profile_images/08_Avocato_Ghostcato.jpg', upload_to='profile_images'),
        ),
    ]
