# Generated by Django 4.1.3 on 2023-03-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_profile_is_published_profile_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Published',
            field=models.BooleanField(default=True, help_text='add profile to contributors'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profile_images/07_Avocato.jpg', upload_to='profile_images'),
        ),
    ]
