# Generated by Django 4.1.3 on 2023-03-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_published_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Published',
            field=models.BooleanField(default=True, help_text='(add profile to contributors)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profile_images/10_Avocato_Abstracato.jpg', upload_to='profile_images'),
        ),
    ]
