# Generated by Django 4.1.3 on 2022-12-12 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Others', max_length=100)),
                ('not_empty', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_catalogue', models.ImageField(upload_to='')),
                ('is_published', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null='False', on_delete=django.db.models.deletion.DO_NOTHING, to='catalogue.category')),
            ],
        ),
    ]
