# Generated by Django 4.1.3 on 2023-05-10 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Others', max_length=100)),
                ('not_empty', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('keywords', models.JSONField(null=True)),
            ],
            options={
                'verbose_name_plural': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('default_hostname', models.CharField(blank='True', max_length=100, null='True')),
                ('image_catalogue', models.ImageField(upload_to='')),
                ('is_published', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null='False', on_delete=django.db.models.deletion.DO_NOTHING, to='catalogue.category')),
                ('keywords', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.DO_NOTHING, to='catalogue.keywords')),
            ],
        ),
    ]
