# Generated by Django 4.1.3 on 2022-12-14 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='keywords',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.DO_NOTHING, to='catalogue.keywords'),
            preserve_default='True',
        ),
    ]
