# Generated by Django 4.1.3 on 2022-12-20 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_catalogue_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='hostname',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='keywords',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.DO_NOTHING, to='catalogue.keywords'),
        ),
    ]
