# Generated by Django 4.1.3 on 2022-12-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_catalogue_hostname_alter_catalogue_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='hostname',
            field=models.CharField(blank='True', max_length=100, null='True'),
        ),
    ]
