# Generated by Django 4.1.3 on 2022-12-20 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_alter_catalogue_hostname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogue',
            old_name='hostname',
            new_name='default_hostname',
        ),
    ]
