# Generated by Django 4.1.3 on 2022-12-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_rename_hostname_catalogue_default_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
