# Generated by Django 4.1.3 on 2022-12-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_keywords_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywords',
            options={'verbose_name_plural': 'keywords'},
        ),
    ]
