# Generated by Django 4.1.3 on 2023-02-13 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_alter_keywords_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
