# Generated by Django 4.1.3 on 2023-05-10 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogue.catalogue')),
            ],
        ),
    ]
