# Generated by Django 4.1.3 on 2022-12-14 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='catalogue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='catalogue.catalogue'),
            preserve_default=False,
        ),
    ]
